#!/usr/bin/env python3
"""Generate standalone fallback descriptors from kv_metrics.yaml."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "kv_semantics/metrics/config/kv_metrics.yaml"
DEFAULT_HEADER = (
    ROOT / "kv_semantics/metrics/include/kv_metrics/default_metric_descriptors.h"
)
SECTIONS = ("counter", "gauge", "histogram")


def load_definitions() -> dict[str, list[dict]]:
    definitions: dict[str, list[dict]] = {section: [] for section in SECTIONS}
    section = ""
    field_pattern = re.compile(r"([a-z_]+):\s*(?:\"((?:\\.|[^\"])*)\"|\[([^\]]*)\])")
    for line_number, raw_line in enumerate(
        SOURCE.read_text(encoding="utf-8").splitlines(), start=1
    ):
        stripped = raw_line.strip()
        if stripped in {f"{name}:" for name in SECTIONS}:
            section = stripped[:-1]
            continue
        if not section or not stripped.startswith("- {"):
            continue
        metric: dict = {}
        for match in field_pattern.finditer(stripped):
            key, quoted, sequence = match.groups()
            if sequence is not None:
                metric[key] = [
                    float(value.strip())
                    for value in sequence.split(",")
                    if value.strip()
                ]
            else:
                metric[key] = json.loads(f'"{quoted}"')
        if not metric:
            raise ValueError(f"cannot parse metric at {SOURCE}:{line_number}")
        definitions[section].append(metric)

    seen_names: set[str] = set()
    for section in SECTIONS:
        for metric in definitions[section]:
            name = metric.get("name", "")
            if not re.fullmatch(r"[a-zA-Z_:][a-zA-Z0-9_:]*", name):
                raise ValueError(f"invalid metric name: {name!r}")
            if name in seen_names:
                raise ValueError(f"duplicate metric name: {name}")
            if not metric.get("documentation"):
                raise ValueError(f"missing documentation for {name}")
            if section == "histogram" and not metric.get("buckets"):
                raise ValueError(f"missing histogram buckets for {name}")
            seen_names.add(name)
    return definitions


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def cpp_number(value: int | float) -> str:
    return repr(value)


def render_default_header(definitions: dict[str, list[dict]]) -> str:
    entries: list[str] = []
    for section in SECTIONS:
        for metric in definitions[section]:
            buckets = metric.get("buckets", [])
            bucket_values = (
                "{" + ", ".join(cpp_number(value) for value in buckets) + "}"
            )
            entries.append(
                "        {"
                f"{cpp_string(metric['name'])}, MetricType::{section.upper()}, "
                f"{cpp_string(metric['documentation'])}, {bucket_values}"
                "},"
            )
    body = "\n".join(entries)
    return f"""#pragma once

// Generated by generate_kv_metrics.py from kv_metrics.yaml.

#include <vector>
#include "kv_metrics/standalone_metrics_backend.h"

namespace kv::metrics {{

inline std::vector<MetricDescriptor> DefaultKvMetricDescriptors()
{{
    return {{
{body}
    }};
}}

}}  // namespace kv::metrics
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="check the standalone fallback header"
    )
    args = parser.parse_args()
    content = render_default_header(load_definitions())
    stale = (
        not DEFAULT_HEADER.exists()
        or DEFAULT_HEADER.read_text(encoding="utf-8") != content
    )
    if args.check:
        if stale:
            print(f"out of date: {DEFAULT_HEADER.relative_to(ROOT)}")
            return 1
        return 0
    if stale:
        DEFAULT_HEADER.write_text(content, encoding="utf-8", newline="\n")
        print(f"generated {DEFAULT_HEADER.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
