#pragma once

// Generated by generate_kv_metrics.py from kv_metrics.yaml.

#include <vector>
#include "kv_metrics/standalone_metrics_backend.h"

namespace kv::metrics {

inline std::vector<MetricDescriptor> DefaultKvMetricDescriptors()
{
    return {
        {"kv_client_batch_load_requests_total",
         MetricType::COUNTER,
         "Total KV client batch-load submissions",                      {}                                                                     },
        {"kv_client_batch_load_entries_total",
         MetricType::COUNTER,
         "Total entries submitted to KV client batch-load operations",  {}                                                                     },
        {"kv_client_batch_load_errors_total",
         MetricType::COUNTER,
         "Total failed KV client batch-load submissions",               {}                                                                     },
        {"kv_client_batch_store_requests_total",
         MetricType::COUNTER,
         "Total KV client batch-store submissions",                     {}                                                                     },
        {"kv_client_batch_store_entries_total",
         MetricType::COUNTER,
         "Total entries submitted to KV client batch-store operations", {}                                                                     },
        {"kv_client_batch_store_errors_total",
         MetricType::COUNTER,
         "Total failed KV client batch-store submissions",              {}                                                                     },
        {"kv_client_batch_load_submit_duration_seconds",
         MetricType::HISTOGRAM,
         "KV client batch-load submission duration",                    {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
        {"kv_client_batch_store_submit_duration_seconds",
         MetricType::HISTOGRAM,
         "KV client batch-store submission duration",                   {1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0}},
    };
}

}  // namespace kv::metrics
